apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - gateway.yaml

namespace: ecommerce-prod

labels:
  - pairs:
      environment: production

secretGenerator:
  - name: app-secrets
    envs:
      - secrets.env
    type: Opaque

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOG_LEVEL
          value: info
